feat(zsh): add quick project selector

diff --git a/configs/zsh/functions b/configs/zsh/functions
--- a/configs/zsh/functions
+++ b/configs/zsh/functions
@@ -56,6 +56,18 @@ flashlight() {
   printf "%s" "$(tput setab "$color")$(tput clear)" && sleep "$duration"
 }
 
+work() {
+  if test -z "$WORKSPACE"; then
+    echo "ERROR: WORKSPACE is not set"
+    return 1
+  fi
+  query=""
+  if test -n "$@"; then
+    query="-q $*"
+  fi
+  cd "$(find "$WORKSPACE" -mindepth 1 -maxdepth 1 -type d | fzf --height=20 '--preview=git -C {} branch' '--bind=ctrl-/:toggle-preview' "$query")" || return
+}
+
 keep() {
   if test $# -eq 0; then
     echo -e "No arguments specified. usage:\necho keep /tmp/test.md\ncat /tmp/test.md | keep test.md"
